- name: Copy DNS Settings
  ansible.builtin.copy:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644' 

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - curl 
      - wget
      - apt-transport-https
      - ca-certificates
      - linux-modules-extra-raspi