- name: Copy DNS Settings
  ansible.builtin.copy:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644' 

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Wait for /var/lib/dpkg/lock-frontend to be released 
  shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;

#- name: Upgrade all apt packages
#  apt: upgrade=dist force_apt_get=yes

- name: install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - curl 
      - wget
      - apt-transport-https
      - ca-certificates
      - linux-modules-extra-raspi

- name: Check if a reboot is needed
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no